### ISSUE TITLE
UnhandledPromiseRejectionWarning when calling /chargeForCookie

### ISSUE THREAD

**Issue by JTorrus** [square/in-app-payments-server-quickstart#8]
I followed the steps shown in this repo and had my app deployed in Heroku for testing purposes. However, the server returns me an error when I call the chargeForCookie POST.

This is the output of my Heroku's application log
```node
2019-01-23T11:09:03.407319+00:00 app[web.1]: Your app is listening on port 7638
2019-01-23T11:09:04.320523+00:00 heroku[web.1]: State changed from starting to up
2019-01-23T11:09:06.794304+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Error: Bad Request
2019-01-23T11:09:06.794316+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:706:15)
2019-01-23T11:09:06.794317+00:00 app[web.1]:     at parser (/app/node_modules/superagent/lib/node/index.js:916:18)
2019-01-23T11:09:06.794319+00:00 app[web.1]:     at IncomingMessage.res.on (/app/node_modules/superagent/lib/node/parsers/json.js:19:7)
2019-01-23T11:09:06.794321+00:00 app[web.1]:     at emitNone (events.js:111:20)
2019-01-23T11:09:06.794322+00:00 app[web.1]:     at IncomingMessage.emit (events.js:208:7)
2019-01-23T11:09:06.794323+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1064:12)
2019-01-23T11:09:06.794325+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
2019-01-23T11:09:06.794326+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:181:9)
2019-01-23T11:09:06.794421+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-01-23T11:09:06.794527+00:00 app[web.1]: (node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is my request code in Dart
```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:square_in_app_payments/models.dart';
import 'package:http/http.dart' as http;

String chargeServerHost = ***********;
String chargeUrl = "$chargeServerHost/chargeForCookie";

class ChargeException implements Exception {
  String errorMessage;
  ChargeException(this.errorMessage);
}

Future<void> chargeCard(CardDetails result) async {
  var body = jsonEncode({"nonce": result.nonce});
  http.Response response;
  try {
    response = await http.post(chargeUrl, body: body, headers: {
      "Accept": "application/json",
      "content-type": "application/json"
    });
  } on SocketException catch (ex) {
    throw ChargeException(ex.message);
  }

  var responseBody = json.decode(response.body);
  if (response.statusCode == 200) {
    return;
  } else {
    throw ChargeException(responseBody["errorMessage"]);
  }
}
```

**Comment by StephenJosey** [comment]
Can you verify you have a nonce (`result.nonce`) either by printing it out or using a debugger? Also does your `chargeServerHost` end with a `/`? If so, can you try removing it since the `chargeUrl` variable includes the back-slash?

If neither of the above is the issue - can you try temporarily changing `on SocketException catch...` to `on Exception catch...` to catch all exceptions since it seems like it's not a type that is being caught here? Hopefully then we would be able to print a better error within the Flutter application.

**Comment by JTorrus** [comment]
I'll check tomorrow if I can make my Node server work by following your advices.

Anyways, I ended up making my own backend with PHP and the Transactions API which works perfectly, but looks like accounts based in my country (Spain) aren't currently supported (gives me an auth error when I make the request to Transactions with the following detail 'You have insufficient permissions to perform that action.'), so I'm afraid I'll have to wait for further support.

Thanks for the answer, Stephen!
